framework:
  rate_limiter:
    login_per_ip:
      policy: sliding_window
      limit: 10
      interval: '1 minute'
      cache_pool: cache.rate_limiter

    login_per_user:
      policy: sliding_window
      limit: 5
      interval: '1 minute'
      cache_pool: cache.rate_limiter

    refresh_per_ip:
      policy: sliding_window
      limit: 60
      interval: '1 minute'
      cache_pool: cache.rate_limiter
