# General controllers (health, metrics)
controllers:
  resource:
    path: ../src/Api/Controller/
    namespace: App\Api\Controller
  type: attribute

#
api_v1:
  resource: ../src/Api/V1/Controller/
  type: attribute
  prefix: /api/v1

